### ISSUE TITLE
Added links cannot click in game?

### ISSUE THREAD

**Issue by djoveryde** [Mineaurion/AurionVoteListener#1]
I've added your plugin to my server however it seems i'm unable to click the url as a link?
Just wondering if i'm missing a plugin to enable that feature or wether its a bug?
I run nucleus on the server, seems urls work fine if you type them in chat but not from the /vote command
Would it be possible to make it so the announcements "Broadcast" as such onto the server so it uses the broadcast command rather than its own?

**Comment by THEJean-Kevin** [comment]
It's me fault,  I forget this. I need just to upload the  new version. I do this when I finish to work
