### ISSUE TITLE
[Suggestion] Time until next vote

### ISSUE THREAD

**Issue by yepidoodles** [Mineaurion/AurionVoteListener#10]
As most vote sites require 24 hrs between votes, I suggest adding a timer which, when you use `/vote`, and have voted in the last 24 hrs, it says something like;

`You have already voted today! Vote again in [x]h[x]m`

Not really a priority, just something helpful to add :)

- Alice Sellars
[DragonTechMC](http://dragontechmc.com)

**Comment by THEJean-Kevin** [comment]
It's hard to implement this because /vote shows just a message and you can put everything in (many link). And the player don't vote directly all the time

**Comment by yepidoodles** [comment]
I was thinking more of a replacement msg, a `if player has voted in last 14 hrs display voteAgainIn voteTime, else voteLinks`

**Comment by Yann151924** [comment]
If you have one link it's possible but like in my case on our server we have like 7-8 link to vote, someone can vote in the first link at the begining of the day and the last at the end. So the time may be wrong.

**Comment by Yann151924** [comment]
Not to be implemented.
