### ISSUE TITLE
Multiple items

### ISSUE THREAD

**Issue by LeChuuck** [Mineaurion/AurionVoteListener#11]
I have setup voting for "ExtraReward" but i have notice that it gives multiple items of the same sort. In the config i have it so it will only give 1 item.

[config.txt](https://github.com/Mineaurion/AurionVoteListener/files/1116958/config.txt)

**Comment by Yann151924** [comment]
Do you say for example, the extra reward is executed multiple times for single vote ? Maybe can be in the service section of the config, you have some command set ? If you can ellaborate more and give the config file except db parameter of course, that really can help :)

**Comment by LeChuuck** [comment]
Yes it executed multiple times for a single vote but its not the same amount every time.
[aurionsvotelistener.txt](https://github.com/Mineaurion/AurionVoteListener/files/1117177/aurionsvotelistener.txt)

**Comment by THEJean-Kevin** [comment]
It's not a bug.  You have just fail your command. 
give <username> lootbags:itemlootbag 3 1 -> this give 3 loot bag with metadata 1. 

give <username> lootbags:itemlootbag 1 3 -> this give 1 loot bag with metadata 3

**Comment by LeChuuck** [comment]
Did not find any documentation about this, thanks for the help.
