### ISSUE TITLE
Request - Config to remove player messages

### ISSUE THREAD

**Issue by yepidoodles** [Mineaurion/AurionVoteListener#12]
Hello,

My request is to add a config turn off the to player reward messages. I tried to remove them myself but just deleting the message, but it still leaves a space in game. They just add more clutter to the chat, and can be confusing, making you think you have the same reward twice (if using the Extra Reward).

[![Screenshot from Gyazo](https://gyazo.com/eed7b18b761b2d557c9dbc7f17ee8396/raw)](https://gyazo.com/eed7b18b761b2d557c9dbc7f17ee8396)

Many thanks,

- Alice

**Comment by THEJean-Kevin** [comment]
I change this on the next version

**Comment by THEJean-Kevin** [comment]
fix in 1.0.8 -> 54605d4
