### ISSUE TITLE
Extra reward and /Vote

### ISSUE THREAD

**Issue by aWitch-Doctor** [Mineaurion/AurionVoteListener#13]
Right now if I set 3 entries in ExtraReward with all of them having 5% chance of being awarded, your plugin will remove 2 of the entries. Any way you can make it so I can have several things in here all with the same chance of being awarded? I have GiveChanceReward set to false so it will only give one of these at a time and I would like all the items to have the same chance of being given.

This next part will tie in with https://github.com/Mineaurion/AurionVoteListener/issues/10

Can you add some info to the /vote command? I would like it to also show a list of all the services (except default) it finds in the config with the name being a clickable link and how long until you can vote again. For the sites that make you wait 24 hours between votes, take the time your plugin receives the vote and save it. For sites that reset at a set time each day just take the timezone info and calculate how long until the site hits that time.

**example:**
You currently have 75 votes.
Planet Minecraft
Minecraft Server List, YOU CAN VOTE NOW!!!
Minecraft Servers, You can vote again in 22 hours.
Minecraft Multiplayer, You can vote again in 10 hours.

The config could list all the info in services.

This will be easier to read, https://hastebin.com/fefivotegi.vbs

> services {
	DEFAULT{
	broadcast="<GREEN><username> <GOLD>has voted @ <GREEN><service> <GOLD>and received <GREEN>5 Diamonds !"
	playermessage="<GREEN>Thanks for voting at <AQUA><service> !"
	commands=[
		"give <username> book 5"
	]
	}
	minecraft-server-list{
	broadcast="<GREEN><username> <GOLD>has voted @ <GREEN> MC-Index <GOLD>and received <GREEN>5 Diamonds !"
	playermessage="<GREEN>Thanks for voting at <AQUA><service> !"
        # What name to display
        sitename="Minecraft Server List"
        # How often will the site let you vote. "daily" (once per 24 hours starting and midnight), "24" (24 hours are needed between votes), leave blank to not show this info.
        time-between-votes="daily"
        # Figure this out to display the correct time for sites that reset the time at midnight. Time is UTC format, Central U.S will be "-6". Only needed if "daily" is entered for time between votes.
        time-zone="-7"
        # Direct URL to your voting page. Needed so you can click the name in game.
        vote-url="http://minecraft-server-list.com/server/"        
	commands=[
		"give <username> book 5"
	]
	}
}

**Comment by THEJean-Kevin** [comment]
Hi,

For your problem with reward, it's normal, I take only 1 entries when GiveChanceReward set to false. I can check for modify this (I thinks I just need to add 1 condition)

It's possible to add some information into /vote command like link, but for the time to vote again, I need to add 1 more Table or file for save Timestamp for every player was voted on every service. And they ask some ressources when saved, and it's not good for server with many player.


What do you think of this :
If in service section you have just DEFAULT, I send just vote's message and I don't save timestamp of vote.
And if in service section, you have others service config like in your exemple, I send this

Service's name -> time before vote again or link for vote

**Comment by aWitch-Doctor** [comment]
I'm not sure exactly what you mean in that last part. can you clarify what you mean by 

> What do you think of this :
If in service section you have just DEFAULT, I send just vote's message and I don't save timestamp of vote.
And if in service section, you have others service config like in your exemple, I send this
Service's name -> time before vote again or link for vote

**Comment by aWitch-Doctor** [comment]
Ok, i think i may have figured it out.

If only default is in services then nothing changes. If there are more sites in services then you will attempt to save the time, and possibly show time and/or link? 

If i understand that correctly then that sounds good to me. Personally I would rather have a clickable link to the site then a time before vote (if we can only have one that is).

**Comment by THEJean-Kevin** [comment]
Ok I try to do this. I don't have so mutch time in this moment but next week I thinks it's ok

**Comment by THEJean-Kevin** [comment]
@aWitch-Doctor 
After some test and documentation. I can do nothing for entries removed. HOCON merge duplicate key.

if someone have the solution, please give it to me

**Comment by aWitch-Doctor** [comment]
That sucks, I'll make it work though. Thank you for trying.

**Comment by Yann151924** [comment]
It's an old issue i will close it, look at the new version and the #10 will not be implemented.
