### ISSUE TITLE
Api 7 please

### ISSUE THREAD

**Issue by aWitch-Doctor** [Mineaurion/AurionVoteListener#14]
I have been using your plugin on everything up to sponge vanilla api 7 beta build 323. I am having to update sponge to the latest version to fix some other bugs and the only plugin im using that hasn't updated is this one. I wasn't expecting it to work, this is mostly asking if you could update to support api 7. I don't currently have a way to test voting without loading the plugin on production and that isn't going to happen. I did try /aurions fakevote and this is the error it gave. 
https://gist.github.com/aWitch-Doctor/8d46bd6d654095e3bd09091b1db758be.js

**Comment by THEJean-Kevin** [comment]
I'm sorry, I've had a lot of trouble with work and school, I'll try to update it this week.

**Comment by THEJean-Kevin** [comment]
fix in 1.0.8 -> 54605d4

**Comment by aWitch-Doctor** [comment]
YAY thank you. You are amazing,
