### ISSUE TITLE
having null error when voting

### ISSUE THREAD

**Issue by JoeSGT** [Mineaurion/AurionVoteListener#16]
hello whenever i do a test vote it give me that error
and here is the current version i am running
Forge - 14.23.1.2555
Sponge - 1.12.2-2529-7.0.0-BETA-2747
AurionVoteListener - 1.0.8
serious-nuvotifier-universal-API7-2.3.5
https://pastebin.com/Tydga00p

**Comment by THEJean-Kevin** [comment]
Can you send me your configuration file without private informations like password

**Comment by JoeSGT** [comment]
oh you sure you need it because i even tried it with default config
but here is it https://pastebin.com/74ZgjnV8

**Comment by THEJean-Kevin** [comment]
Last question, when you test vote, do you get reward?

**Comment by JoeSGT** [comment]
no not at all

**Comment by THEJean-Kevin** [comment]
Can you tell me if this version correct your problem (you need to unzip )
[AurionsVoteListener-1.0.8.zip](https://github.com/Mineaurion/AurionVoteListener/files/1521390/AurionsVoteListener-1.0.8.zip)

**Comment by JoeSGT** [comment]
thanks it work!

**Comment by THEJean-Kevin** [comment]
thx you for report error
