### ISSUE TITLE
Null error when players join the server

### ISSUE THREAD

**Issue by JoeSGT** [Mineaurion/AurionVoteListener#17]
Hello basically getting this error when someone join the server, I'll list my version that i am using 
```
SpongeForge: 1.12.2-2611-7.1.0-BETA-2944
AurionVoteListener: 1.0.9
```
Error: https://gist.github.com/JoeSGT/bae91e544a57403e958841b34e793b1e

**Comment by JoeSGT** [comment]
Just closing this i switch to mysql and it seem it's a better database then the default one.

**Comment by JoeSGT** [comment]
https://pastebin.com/raw/YH7pk446 it seem to happen random and player cannot join i do have mysql installed

**Comment by THEJean-Kevin** [comment]
I modify the var cause the null error
[plugin.zip](https://github.com/Mineaurion/AurionVoteListener/files/2095751/plugin.zip)

**Comment by JoeSGT** [comment]
Thanks you, I'll let you know if the issue kept is still there
