### ISSUE TITLE
Errors/commands not working

### ISSUE THREAD

**Issue by liampearson96** [Mineaurion/AurionVoteListener#18]
Hello, just updated to your recent plugin update, after updating the force queue command doesnt work, also fakevote doesn't work either, i get this error when trying to run forcequeue Error occurred while executing command: null. please could you help. Thanks

**Comment by liampearson96** [comment]
Server thread/ERROR [Sponge]: Error occurred while executing command 'aurions forcequeue' for source EntityPlayerMP['liampearson1996'/7156, l='World', x=1853.58, y=37.00, z=3266.42]: null
31.03 09:53:20 [Server] INFO java.lang.NullPointerException: null
31.03 09:53:20 [Server] INFO at com.mineaurion.aurionVoteListener.SQL.SwitchSQL.QueuePlayer(SwitchSQL.java:213) ~[SwitchSQL.class:?]
31.03 09:53:20 [Server] INFO at com.mineaurion.aurionVoteListener.commands.ForcequeueCmd.execute(ForcequeueCmd.java:24) ~[ForcequeueCmd.class:?]
31.03 09:53:20 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2611-7.1.0-BETA-2990]
31.03 09:53:20 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2611-7.1.0-BETA-2990]
31.03 09:53:20 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2611-7.1.0-BETA-2990]
31.03 09:53:20 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2611-7.1.0-BETA-2990]
31.03 09:53:20 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
31.03 09:53:20 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
31.03 09:53:20 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
31.03 09:53:20 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
31.03 09:53:20 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
31.03 09:53:20 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2990]
31.03 09:53:20 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539) [hv$1.class:?]
31.03 09:53:20 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
31.03 09:53:20 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
31.03 09:53:20 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
31.03 09:53:20 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
31.03 09:53:20 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2990]
31.03 09:53:20 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3977) [MinecraftServer.class:?]
31.03 09:53:20 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
31.03 09:53:20 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
31.03 09:53:20 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
31.03 09:53:20 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
31.03 09:53:20 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by THEJean-Kevin** [comment]
Hello, Can you try to do /sponge plugins reload and tell me if the command works after

**Comment by liampearson96** [comment]
Yeah, still doesn't work, restarted server multiple times as well

**Comment by THEJean-Kevin** [comment]
Ok, I need the full log of your server to find when the connection is closed? For this, you can connect to my discord https://discord.gg/C7eamD and send me a PM with the full log

**Comment by liampearson96** [comment]
Your discord link isnt working add me please liampearson1996#3673

I believe the new version of griefprevention stops the vote plugin from working. i just tested this.

**Comment by THEJean-Kevin** [comment]
related to #19 
corrected with https://github.com/Mineaurion/AurionVoteListener/releases/tag/2.1bis
