### ISSUE TITLE
Error connection is close

### ISSUE THREAD

**Issue by JoeSGT** [Mineaurion/AurionVoteListener#19]
https://hastebin.com/abocobuyis.vbs
I am not sure what this means but the mysql info is right

**Comment by THEJean-Kevin** [comment]
Can you tell me this informations : 
Version officielle aurionvotelistener
Do you have reload thé plugin with /sponge plugins reload

**Comment by JoeSGT** [comment]
I versions i have is
aurionvotelistener: 1.0.9 and tried updating to 2.0
SpongeForge: 1.12.2-2655-7.1.0-BETA-3051

I have not reload anything this error happens ever someone join the server and it does not give any rewards

**Comment by THEJean-Kevin** [comment]
can you send me the log of the server startup (when the plugins this load).
If you want you can send me this in mp on discord : discord.gg/Zn4ZbP9

**Comment by THEJean-Kevin** [comment]
I have found an error in my code. Can you tell me if you still have the mistake


[plugin.zip](https://github.com/Mineaurion/AurionVoteListener/files/1960302/plugin.zip)

**Comment by JoeSGT** [comment]
it works! with the plugin.zip you provided still want those errors?
Thanks you

**Comment by THEJean-Kevin** [comment]
with plugin.zip, normally it corrects errors

**Comment by JoeSGT** [comment]
Yea it fixed it, i though you wanted the errors from the old version sorry

**Comment by JoeSGT** [comment]
https://hastebin.com/irifulacos.rb
sorry but it seem it's broken it work for some players but not all 
it's very weird and strange bug

**Comment by JoeSGT** [comment]
more error's https://hastebin.com/arexodizag.rb

**Comment by THEJean-Kevin** [comment]
try this, I change all code for Sql connection
[plugin.zip](https://github.com/Mineaurion/AurionVoteListener/files/1963625/plugin.zip)

**Comment by JoeSGT** [comment]
it work! and made sure of it! thanks again and sorry for the long wait
