### ISSUE TITLE
infinite rewards due to a database

### ISSUE THREAD

**Issue by JoeSGT** [Mineaurion/AurionVoteListener#23]
so i don't know if it's mysql at fault or the plugin but ever since i update this plugin i had been getting a bug where players can join and leave and keep getting offline rewards here the error https://hastebin.com/ekisufikab.shell
and this happen i have to keep clearing out the queue

**Comment by THEJean-Kevin** [comment]
do you have take 2.4.1 I correct this on this version

**Comment by JoeSGT** [comment]
oops sorry normally i put the verison number down but i forgot i use `AurionVoteListener.2.4.API.7` i didn't see that it update it already ill update and ill close this issue but if it happen again ill reopen it thanks you
