### ISSUE TITLE
How to add Website's?

### ISSUE THREAD

**Issue by glennpronl** [Mineaurion/AurionVoteListener#27]
Hi,

i really want to let this plugin work on my server. but i dont know how i can add a vote site on it.
It says on the site that i need an Votifier IP Votifier port and an votifier public key. where can i find this?

**Comment by demonte4509ui** [comment]
having the same issue the devs are pretty much useless I tried their discord and they wont help anyone

**Comment by Yann151924** [comment]
Sorry for the late response and thanks to the latest answer.
If you want to add any website you need to have nuvotifier installed on your server. Nuvotifier has a doc here : https://github.com/parallelblock/NuVotifier/blob/master/docs/usage.md
