### ISSUE TITLE
Apparent connection leak detected

### ISSUE THREAD

**Issue by runescapejon** [Mineaurion/AurionVoteListener#28]
https://pastebin.com/raw/vDVL3xcK
Versions i have is 
- AurionVoteListener-2.4.2-S7.1.0
- spongeforge-1.12.2-2768-7.1.5 
- serious-nuvotifier-universal-API7-2.3.5 

Basically getting this error whenever the server start up really have no clue but it seem that it's coming from mysql not sure if it's the plugin at fault or my end.

**Comment by Rasgnarok** [comment]
![image](https://user-images.githubusercontent.com/18584380/62824705-f5233500-bb6f-11e9-81df-0ecc430012d3.png)
having it myself, any updates?

**Comment by Yann151924** [comment]
The connection leak is fixed in the last version, it's still in beta but you can test it if you want.

**Comment by KhaozFrost** [comment]
still a bug in the latest version.
https://gist.github.com/KhaozFrost/4973241ff1256d06d99b576d8855ee51

**Comment by KhaozFrost** [comment]
https://gist.github.com/KhaozFrost/4973241ff1256d06d99b576d8855ee51

**Comment by Yann151924** [comment]
Please update to 2.5.6 and open a new issue if the bug is still existant
