### ISSUE TITLE
Error Spam

### ISSUE THREAD

**Issue by CyberSpongie** [Mineaurion/AurionVoteListener#3]
Hello thanks for making this!,
i am having this error spamming in the console i am unsure how to fix https://pastebin.com/RN0k8GMq
SpongeForge: 1.10.2-2281-5.2.0-BETA-227
 Forge: 12.18.3.2185

**Comment by THEJean-Kevin** [comment]
Thx for you report. I check today what is the problem.
If i understand you used File mode?

**Comment by CyberSpongie** [comment]
yes

**Comment by THEJean-Kevin** [comment]
do you have discord?
if you have https://discordapp.com/invite/px5Mq8y and contact me. I would like to try something with you

**Comment by THEJean-Kevin** [comment]
Fix in V1.0.4
