### ISSUE TITLE
Advanced Rewards executing three times permission rewards

### ISSUE THREAD

**Issue by runescapejon** [Mineaurion/AurionVoteListener#30]
My version are 
- AurionVoteListener-2.4.2-S7.1.0
- SpongeForge -1.12.2-2768-7.1.6-RC3616
My issue is on the Advanced reward i did a broadcast test and a simple give command it's giving me the rewards three times not just once also i had give me the permission directly not by group i am using using luckperms version 4.3.109

**Comment by Yann151924** [comment]
Related to #36
