### ISSUE TITLE
commands doesn't works

### ISSUE THREAD

**Issue by SlendyOff** [Mineaurion/AurionVoteListener#31]
when i run /vote nothings happends :l 

NuVotifier version: nuvotifier-2.5.0
AurionVoteListener version: AurionVoteListener-2.5-S7.1.0
Sponge version:  Sponge 1.12.2-2768-7.1.4 Stable

**Comment by Yann151924** [comment]
Use the 2.4 version for now, the 2.5 version is a prelease and there is lack of message to help you out setup it :). When the 2.5 is done i will update all the docs and the readme 😉

**Comment by SlendyOff** [comment]
ok ty!
