### ISSUE TITLE
chance rewards

### ISSUE THREAD

**Issue by ThePro1604** [Mineaurion/AurionVoteListener#33]
when im trying to set up the chance reward im always getting only one specific reward from it all the time

im always getting the random poke rewards and none of the others

ExtraReward{
	"1"{
		broadcast="<GREEN><username> <GOLD>was Extremly lucky and received a <GREEN>Random Legendary"
		playermessage="<GREEN>You were Extremly lucky and received a <GREEN> Random Legendary "
		commands=[
			"randomleg <username> 70"
		]
	}
	"2"{
		broadcast="<GREEN><username> <GOLD>was super lucky and received a <GREEN>Random Shiny"
		playermessage="<GREEN>You were Super lucky and received a Random Shiny"
		commands=[
			"pokerandom <username> s"
		]
	}
	"3"{
		broadcast="<GREEN><username> <GOLD>was lucky and received a <GREEN> Master Ball"
		playermessage="<GREEN>You were lucky and received a <GREEN> Master Ball "
		commands=[
			"give <username> pixelmon:master_ball 1"
		]
	}
	"30"{
		broadcast="<GREEN><username> <GOLD>received <GREEN>1 Bonus Coin"
		playermessage="<GREEN>You received <GREEN>1 Bonus Coin "
		commands=[
			"adminpay <username> 1 coin"
		]
	}
	"5.3"{
		broadcast="<GREEN><username> <GOLD> received  <GREEN>1 Bonus Poke Ball"
		playermessage="<GREEN>You received <GREEN>1 Bonus Poke Ball"
		commands=[
			"give <username> pixelmon:pokeball_ball 1"
		]
	}
	"5.2"{
		broadcast="<GREEN><username> <GOLD> received  <GREEN>1 Bonus Ultra Ball"
		playermessage="<GREEN>You received <GREEN>1 Bonus Poke Ball"
		commands=[
			"give <username> pixelmon:ultra_ball 1"
		]
	}
	"5.1"{
		broadcast="<GREEN><username> <GOLD> received  <GREEN>1 Bonus Great Ball"
		playermessage="<GREEN>You received <GREEN>1 Bonus Poke Ball"
		commands=[
			"give <username> pixelmon:great_ball 1"
		]
	}
	"5"{
		broadcast="<GREEN><username> <GOLD>was Very lucky and received a <GREEN>Random Poke"
		playermessage="<GREEN>You were Very lucky and received a <GREEN> Random Poke "
		commands=[
			"pokerandom <username>"
		]
	}

}

**Comment by Yann151924** [comment]
Related to #36
