### ISSUE TITLE
[Suggestion] Allow top donator reward

### ISSUE THREAD

**Issue by NLBlacky** [Mineaurion/AurionVoteListener#37]
Would be amazing if AurionsVoteListener would support top donator rewards. With config options you could set if you want daily / weekly / monthly top donator rewards and after the reward was given (on the next time the player goes on but with a timeout to avoid endless waiting for non returning players?) the voting would be resetted for the new period of time.

**Comment by Yann151924** [comment]
I don't think i will add this kind of stuff in the plugin. This will a be a lot of effort for a thing that you can do in Bash script for just 5 line :). It's better to do things like this in "external way". I can provide an SQL request but not the logical part when you execute the command on your server.

**Comment by Yann151924** [comment]
Related to #34.

**Comment by Yann151924** [comment]
Closing favor to previous comment, related issue.
