### ISSUE TITLE
Request: Top Vote Rewards [Weekly/Monthly] (Enhancement)

### ISSUE THREAD

**Issue by KhaozFrost** [Mineaurion/AurionVoteListener#39]
something like this:

weekly_rewards:
  first_place:
    positions:
    - 1
    actions:
    - '[GiveItem] DIAMOND;64'
    - '[Message] &c[&c&lVOTES&c] &7You finished &a&l1st Place &7with the most weekly
      votes! &7(&b%weekly_votes% votes&7)'
  second_place:
    positions:
    - 2
    actions:
    - '[GiveItem] DIAMOND;64'
    - '[Message] &c[&c&lVOTES&c] &7You finished &a&l1st Place &7with the most weekly
      votes! &7(&b%weekly_votes% votes&7)'
  third_place:
    positions:
    - 3
    actions:
    - '[GiveItem] DIAMOND;64'
    - '[Message] &c[&c&lVOTES&c] &7You finished &a&l1st Place &7with the most weekly
      votes! &7(&b%weekly_votes% votes&7)'
  other_place:
    positions:
    - 4
    - 5
    - 6
    actions:
    - '[GiveItem] DIAMOND;64'
    - '[Message] &c[&c&lVOTES&c] &7You finished &a&l1st Place &7with the most weekly
      votes! &7(&b%weekly_votes% votes&7)'
monthly_rewards:
  first_place:
    positions:
    - 1
    actions:
    - '[GiveItem] DIAMOND;64'
    - '[Message] &c[&c&lVOTES&c] &7You finished &a&l1st Place &7with the most weekly
      votes! &7(&b%weekly_votes% votes&7)'
  second_place:
    positions:
    - 2
    actions:
    - '[GiveItem] DIAMOND;64'
    - '[Message] &c[&c&lVOTES&c] &7You finished &a&l1st Place &7with the most weekly
      votes! &7(&b%weekly_votes% votes&7)'
  third_place:
    positions:
    - 3
    actions:
    - '[GiveItem] DIAMOND;64'
    - '[Message] &c[&c&lVOTES&c] &7You finished &a&l1st Place &7with the most weekly
      votes! &7(&b%weekly_votes% votes&7)'
  other_place:
    positions:
    - 4
    - 5
    - 6
    actions:
    - '[GiveItem] DIAMOND;64'
    - '[Message] &c[&c&lVOTES&c] &7You finished &a&l1st Place &7with the most weekly
      votes! &7(&b%weekly_votes% votes&7)'

**Comment by Yann151924** [comment]
Related to #34 #37

**Comment by Yann151924** [comment]
Closing in favor of standlone solution quoted in previous comment.
