### ISSUE TITLE
Apparent connection leak detected

### ISSUE THREAD

**Issue by ChrisRobby970** [Mineaurion/AurionVoteListener#41]
Just downloaded this version and it put this warning.

https://gyazo.com/62e02ec55d27e523acec047eb213ce46

**Comment by Yann151924** [comment]
This leak appear all the time ? Or just at the start ?

**Comment by ChrisRobby970** [comment]
Oh, I think it only happens on the first time startup? because I got reinstalled, loaded new config ect. and it did it but when restarting while I keep it, doesnt do it so technically fixed for me.

**Comment by Yann151924** [comment]
I close the issue, if this happen again re-open the issue.
