### ISSUE TITLE
Crash and burn

### ISSUE THREAD

**Issue by LeChuuck** [Mineaurion/AurionVoteListener#5]
After updating sponge the server crashes with "AurionVoteListener".
[crash-2017-06-01_05.45.15-server.txt](https://github.com/Mineaurion/AurionVoteListener/files/1043590/crash-2017-06-01_05.45.15-server.txt)

spongeforge-1.10.2-2281-5.2.0-BETA-2353

**Comment by Yann151924** [comment]
nuvotifier is installed on your server ?

**Comment by LeChuuck** [comment]
Did recently update the pack as well and must have forgetten nuvotifier, works like a charm now.
