### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by unovalegends** [Mineaurion/AurionVoteListener#6]
Okay I ran into a couple of issue 1 when people do /vote or /votetop it says unknown command as if it crashed. Two I have no errors in my console which is confusing .

I want to provide links when players to /vote I dont know if I am doing this right I need help here my config

https://pastebin.com/6LigkZHX

**Comment by Yann151924** [comment]
Can you provide the consol log ?

**Comment by THEJean-Kevin** [comment]
Hy, I can Check the problem if you don't send log,

**Comment by THEJean-Kevin** [comment]
No additional information
