### ISSUE TITLE
Issue with links

### ISSUE THREAD

**Issue by FiveEYZ** [Mineaurion/AurionVoteListener#7]
links ending with / dont work, some vote sites require the / to be there

**Comment by FiveEYZ** [comment]
problem is that this plugin remove the / at the end of links

**Comment by THEJean-Kevin** [comment]
Thx to report, I will check for modify this, 
But my job takes me too long at the moment

So I don't know when I post an update (maybe 2 weeks)

**Comment by THEJean-Kevin** [comment]
Fix in releases 1.0.7 ->  6f2c185
