### ISSUE TITLE
ExtraReward issue

### ISSUE THREAD

**Issue by FiveEYZ** [Mineaurion/AurionVoteListener#8]
cant get this one to work, have `AddExtraReward=true` and `GiveChanceReward=true` but the "extra" is never given.

tried 100 fakevotes with 1 ExtraReward at 20%, not a single reward was given

**Comment by yepidoodles** [comment]
Also getting this issue

**Comment by THEJean-Kevin** [comment]
Thx to report the bug, I will check the problem in the coming week. My job take me to many time at the moment

**Comment by THEJean-Kevin** [comment]
Fix in releases 1.0.7 ->  6f2c185
