### ISSUE TITLE
Improvement Suggestion - Offline votes

### ISSUE THREAD

**Issue by yepidoodles** [Mineaurion/AurionVoteListener#9]
Currently, with `broadcastoffline=false`, once a player logs in they get every single vote message from their votes. So if a player voted on the 5 sites 5 days in a row, when they logged in, it would display 25 vote site messages.... Not ideal. 

So my suggestion is that instead of those vote messages, it displays a single message which says something like:
`<player> voted <amt> times while they were offline and received rewards!`

Would cut down your spam, and add something which none of the other vote sites add currently.

- Alice
[DragonTechMC](http://dragontechmc.com)

**Comment by Yann151924** [comment]
We think the same things to add :)

**Comment by THEJean-Kevin** [comment]
Nice idea, I correct some bug before to implement this

**Comment by THEJean-Kevin** [comment]
Implement in releases 1.0.7 ->  6f2c185
